YARN-8919. Some tests fail due to NoClassDefFoundError for OperatorCreationException (tasanuma0829 via rkanter)
Former-commit-id: 5e294e950b9d1b6f852f2d3467a9809a82f9860e